### ISSUE TITLE
Analyze dependency monkey results for inspection-2020-09-08.1

### ISSUE THREAD

**Issue by fridex** [thoth-station/datasets#16]
Results of inspection https://github.com/thoth-station/dependency-monkey-zoo/tree/master/tensorflow/inspection-2020-09-08.1 should be available for analysis. Based on their results, we can adjust https://github.com/thoth-station/adviser/pull/1172 so that our recommendation engine recommends working `tensorflow==2.1` stacks without the issue described in https://github.com/thoth-station/notebooks/issues/70#issuecomment-688664537.

**Comment by pacospace** [comment]
> Results of inspection https://github.com/thoth-station/dependency-monkey-zoo/tree/master/tensorflow/inspection-2020-09-08.1 should be available for analysis. Based on their results, we can adjust [thoth-station/adviser#1172](https://github.com/thoth-station/adviser/pull/1172) so that our recommendation engine recommends working `tensorflow==2.1` stacks without the issue described in [thoth-station/notebooks#70 (comment)](https://github.com/thoth-station/notebooks/issues/70#issuecomment-688664537).

Analyzing the dataset we can see the versions that actually fails with `six` and `urllib3`:

```
=============================================

 six

=============================================

In successfull inspections:

['six-1.13.0-pypi-org' 'six-1.12.0-pypi-org']

In failed inspections:

['six-1.13.0-pypi-org']

In failed inspections but not in successfull:

set()

In failed inspections and in successfull:

{'six-1.13.0-pypi-org'}

=============================================

 urllib3

=============================================

In successfull inspections:

['urllib3-1.23-pypi-org' 'urllib3-1.21.1-pypi-org'
 'urllib3-1.10.3-pypi-org' 'urllib3-1.18-pypi-org' 'urllib3-1.22-pypi-org'
 'urllib3-1.25.3-pypi-org' 'urllib3-1.8.2-pypi-org'
 'urllib3-1.10.2-pypi-org' 'urllib3-1.24-pypi-org' 'urllib3-1.13-pypi-org'
 'urllib3-1.24.1-pypi-org' 'urllib3-1.21-pypi-org' 'urllib3-1.9-pypi-org'
 'urllib3-1.25-pypi-org' 'urllib3-1.10-pypi-org' 'urllib3-1.25.1-pypi-org'
 'urllib3-1.12-pypi-org' 'urllib3-0.3-pypi-org' 'urllib3-1.10.4-pypi-org'
 'urllib3-1.25.5-pypi-org' 'urllib3-1.24.2-pypi-org'
 'urllib3-1.18.1-pypi-org' 'urllib3-1.25.4-pypi-org'
 'urllib3-1.10.1-pypi-org' 'urllib3-1.6-pypi-org'
 'urllib3-1.15.1-pypi-org' 'urllib3-1.19.1-pypi-org'
 'urllib3-1.25.7-pypi-org' 'urllib3-1.25.2-pypi-org'
 'urllib3-1.13.1-pypi-org' 'urllib3-1.24.3-pypi-org'
 'urllib3-1.11-pypi-org' 'urllib3-1.20-pypi-org' 'urllib3-1.8.3-pypi-org'
 'urllib3-1.15-pypi-org' 'urllib3-1.25.6-pypi-org' 'urllib3-1.14-pypi-org'
 'urllib3-1.19-pypi-org' 'urllib3-1.17-pypi-org' 'urllib3-1.9.1-pypi-org'
 'urllib3-1.7.1-pypi-org' 'urllib3-1.16-pypi-org' 'urllib3-1.7-pypi-org'
 'urllib3-1.8-pypi-org']

In failed inspections:

['urllib3-1.5-pypi-org' 'urllib3-1.4-pypi-org' 'urllib3-1.2-pypi-org'
 'urllib3-1.2.2-pypi-org' 'urllib3-1.3-pypi-org']

In failed inspections but not in successfull:

{'urllib3-1.2.2-pypi-org', 'urllib3-1.4-pypi-org', 'urllib3-1.5-pypi-org', 'urllib3-1.3-pypi-org', 'urllib3-1.2-pypi-org'}

In failed inspections and in successfull:

set()
```

**Comment by pacospace** [comment]
![Screenshot from 2020-09-10 12-48-45](https://user-images.githubusercontent.com/27498679/92719805-0090f300-f364-11ea-9404-bbf5903dbf72.png)

**Comment by fridex** [comment]
Awesome, we can adjust the pipeline unit accordingly. Thanks! :+1:

**Comment by pacospace** [comment]
> Awesome, we can adjust the pipeline unit accordingly. Thanks!

I ll add the dataset and notebook and show what we can do with this type of datasets :)

**Comment by fridex** [comment]
Pipeline unit updated. Created justification document in https://github.com/thoth-station/thoth-station.github.io/pull/116/files PTAL We can add the notebook there once published :+1:

**Comment by pacospace** [comment]
> Pipeline unit updated. Created justification document in https://github.com/thoth-station/thoth-station.github.io/pull/116/files PTAL We can add the notebook there once published

Very nice!! sure we can do!!
