### ISSUE TITLE
Analyze inspection-2020-09-13

### ISSUE THREAD

**Issue by fridex** [thoth-station/datasets#21]
Let's analyze another dependency monkey run batch:

https://github.com/thoth-station/dependency-monkey-zoo/tree/master/tensorflow/inspection-2020-09-13#inspection-2020-09-13

I saw a lot of failures caused by an inaccessible container registry, hence builds failed.

**Comment by fridex** [comment]
The batch hasn't finished yet, but should be available later today.

**Comment by pacospace** [comment]
I'll start exploring this new dataset for identifier `tf-dm-rw3`

**Comment by fridex** [comment]
No longer relevant. Closing.
