### ISSUE TITLE
Analyze inspection inspection-2021-02-09

### ISSUE THREAD

**Issue by fridex** [thoth-station/datasets#23]
**Is your feature request related to a problem? Please describe.**

Inspection  `inspection-2021-02-09` finished and results are available on Ceph. Let's analyze them. See https://github.com/thoth-station/dependency-monkey-zoo/tree/master/tensorflow/inspection-2021-02-09 with all the relevant information.

**Describe the solution you'd like**

Check what went wrong and if there are any relevant failures from which we could conduct recomendations.

**Comment by fridex** [comment]
Some failed ones have issues with pushing the resulting container image.

**Comment by pacospace** [comment]
@fridex in which bucket are stored the data?

```
 aws s3 --profile thoth --endpoint https://s3.upshift.redhat.com/ ls s3://thoth/data/ocp-stage/inspections/inspection-tf-dm-tf24-23d24403/
```
`inspection-tf-dm-tf24-23d24403` first in the list for this analysis does not exists at that path

**Comment by fridex** [comment]
They should be stored in `ocp4-stage`.

**Comment by pacospace** [comment]
> They should be stored in `ocp4-stage`.

aaa make sense, thanks @fridex!!

**Comment by pacospace** [comment]
After initial analysis of this dataset, `801` inspections have been identified. These inspections have been created for different stack combination of TensorFlow 2.4.0 on ubi8 for python38.

**inspection builds failed**

- 72 failed during builds.

After further analysis of this failed builds, we discovered that:

** CASE 1: 27 are due to push error with the following logs:

```
error: build error: Failed to push image: error copying layers and metadata from "containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.imagestore=/var/lib/shared]image-registry.openshift-image-registry.svc:5000/thoth-amun-inspection-stage/inspection-tf-dm-tf24-ID:latest" to "docker://image-registry.openshift-image-registry.svc:5000/thoth-amun-inspection-stage/inspection-tf-dm-tf24-ID:latest": Error writing manifest: Error uploading manifest latest to image-registry.openshift-image-registry.svc:5000/thoth-amun-inspection-stage/inspection-tf-dm-tf24-ID: manifest blob unknown: blob unknown to registry
```

** CASE 2: 19 appear to have been caused by some external source (maybe timeout?):

```
Error: received unexpected terminate signal
```

** CASE 3: 6 cases can be associated to CASE 1 after checking similar errors.

```
Push successful
```
** CASE 4: 2 cases where build finished successfully but inspection run did not start. From build logs we can see:

Push successful

** CASE 5: Missing 18 cases of inspections did not contain any logs, as they were not present on Ceph:

```
Failed to retrieve object, object 'log' does not exist
```

**inspection with results**

Analyzing the other 729 inspections:

** 0 inspections runs failed identified. No differences in 

It appears this dataset does not contain failures that we can investigate to provide a new recommendation to users.

If no further investigations are requested, I would proceed clearning the notebook, prepare the dataset and publish everything in this repo.

@fridex any thoughts?

**Comment by fridex** [comment]
> It appears this dataset does not contain failures that we can investigate to provide a new recommendation to users.

Great, thanks for this work :+1: 

> If no further investigations are requested, I would proceed adding some plots for performance maybe, cleaning the notebook, prepare the dataset and publish everything in this repo.
>
> @fridex any thoughts?

Any reason to clean the notebook? We can keep it as is with cells produced, just in case we would like to have a look or show it off. Otherwise big +1 on my side.

Thanks! :beers:

**Comment by pacospace** [comment]
> > It appears this dataset does not contain failures that we can investigate to provide a new recommendation to users.
> 
> Great, thanks for this work 
> 
> > If no further investigations are requested, I would proceed adding some plots for performance maybe, cleaning the notebook, prepare the dataset and publish everything in this repo.
> > @fridex any thoughts?
> 
> Any reason to clean the notebook? We can keep it as is with cells produced, just in case we would like to have a look or show it off. Otherwise big +1 on my side.

Sorry by clean I do not mean cleaning the outputs from cells, just some part of the code currently created :)
> 
> Thanks!

Another interesting thing about performance identified from this dataset:

![TF==2 4 0 performance (2D plot)](https://user-images.githubusercontent.com/27498679/111445916-27adf000-870c-11eb-84ce-90160df47297.png)

It apperas there is one stack which is way more performant than others, identified by ID: 558, which corresponds to software stack:
```
tensorflow-2.4.0-pypi-org-simple
typing-extensions-3.7.4.3-pypi-org-simple
wrapt-1.12.1-pypi-org-simple
grpcio-1.32.0-pypi-org-simple
wheel-0.35.1-pypi-org-simple
keras-preprocessing-1.1.2-pypi-org-simple
opt-einsum-3.3.0-pypi-org-simple
numpy-1.19.4-pypi-org-simple
tensorflow-estimator-2.4.0-pypi-org-simple
gast-0.3.3-pypi-org-simple
flatbuffers-1.12-pypi-org-simple
absl-py-0.11.0-pypi-org-simple
h5py-2.10.0-pypi-org-simple
astunparse-1.6.3-pypi-org-simple
termcolor-1.1.0-pypi-org-simple
protobuf-3.12.1-pypi-org-simple
six-1.15.0-pypi-org-simple
setuptools-46.1.2-pypi-org-simple
tensorboard-2.4.0-pypi-org-simple
google-pasta-0.2.0-pypi-org-simple
werkzeug-0.15.2-pypi-org-simple
requests-2.24.0-pypi-org-simple
google-auth-1.11.0-pypi-org-simple
pyasn1-modules-0.2.3-pypi-org-simple
tensorboard-plugin-wit-1.6.0.post2-pypi-org-simple
pyasn1-0.4.4-pypi-org-simple
rsa-3.2.2-pypi-org-simple
idna-2.5-pypi-org-simple
urllib3-1.25.4-pypi-org-simple
cachetools-4.2.0-pypi-org-simple
markdown-3.1-pypi-org-simple
certifi-2018.10.15-pypi-org-simple
google-auth-oauthlib-0.4.2-pypi-org-simple
chardet-3.0.4-pypi-org-simple
requests-oauthlib-1.3.0-pypi-org-simple
oauthlib-3.0.1-pypi-org-simple
```

we can notice that numpy-1.19.4-pypi-org-simple  is not the latest version of numpy actually.

So I wanted to check if we can compare with stack created by pipenv. So I installed `tensorflow==2.4.0` with pipenv and noticed that `numpy==1.19.5` as we can see from the stack below:

```
absl-py==0.12.0
aiohttp==3.7.4.post0
appdirs==1.4.4
argo-workflows==3.6.1
astunparse==1.6.3
async-timeout==3.0.1
attrdict==2.0.1
attrs==20.3.0
beautifulsoup4==4.6.3
cachetools==4.2.1
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
colorama==0.4.4
commonmark==0.9.1
daiquiri==3.0.0
delegator.py==0.1.1
dictdiffer==0.8.1
distlib==0.3.1
distro==1.5.0
filelock==3.0.12
flatbuffers==1.12
gast==0.3.3
google-auth==1.28.0
google-auth-oauthlib==0.4.3
google-pasta==0.2.0
grpcio==1.32.0
h5py==2.10.0
idna==2.10
invectio==0.1.0
Jinja2==2.11.3
jsonformatter==0.3.1
jsonschema==3.2.0
Keras-Preprocessing==1.1.2
kubernetes==11.0.0
lxml==4.6.2
Markdown==3.3.4
MarkupSafe==1.1.1
micropipenv==1.0.3
mock==4.0.3
multidict==5.1.0
numpy==1.19.5
oauthlib==3.1.0
openshift==0.11.0
opt-einsum==3.3.0
packaging==20.9
pexpect==4.8.0
protobuf==3.15.6
ptyprocess==0.7.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyelftools==0.27
Pygments==2.8.1
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
python-json-logger==2.0.1
python-string-utils==1.0.0
pytz==2021.1
PyYAML==5.4.1
requests==2.25.1
requests-oauthlib==1.3.0
rfc5424-logging-handler==1.4.3
rich==9.13.0
rsa==4.7.2
ruamel.yaml==0.16.13
ruamel.yaml.clib==0.2.2
semantic-version==2.8.5
sentry-sdk==1.0.0
six==1.15.0
tensorboard==2.4.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.4.0
tensorflow-estimator==2.4.0
termcolor==1.1.0
thamos==1.15.0
thoth-analyzer==0.1.8
thoth-common==0.26.0
thoth-python==0.15.5
toml==0.10.2
typing-extensions==3.7.4.3
tzlocal==2.1
urllib3==1.26.4
virtualenv==20.4.3
websocket-client==0.58.0
Werkzeug==1.0.1
wrapt==1.12.1
yarl==1.6.3
yaspin==1.4.1
```

Unfortunately, the inspections runs stacks in this dataset do not have any `numpy==1.19.5` used with tensorflow 2.4.0, is that normal @fridex ?

These are numpy found in all 729 stacks:

```
$ final_dataframe['numpy'].unique()

array(['numpy-1.19.4-pypi-org-simple', 'numpy-1.19.0-pypi-org-simple',
       'numpy-1.18.5-pypi-org-simple'], dtype=object)
```

**Comment by fridex** [comment]
> > Thanks!
> 
> Another interesting thing about performance identified from this dataset:
> 
> ![TF==2 4 0 performance (2D plot)](https://user-images.githubusercontent.com/27498679/111445916-27adf000-870c-11eb-84ce-90160df47297.png)
> 
> It apperas there is one stack which is way more performant than others, identified by ID: 558, which corresponds to software stack:
> 
> ```
> ...
> ```

Not sure if I follow this - the plot shows 3 potentially separable performance lines. If I read the the plot correctly, there could be package combinations that create this separation (if we are not hitting different hardware nodes in the cluster that have different performance) - yellow, purple and orange lines. To my understanding of the plot, we would like to know why software stacks encoded with yellow dots are performing better than the rest. If there are no hardware configuration differences, we could try to cluster software stacks based on vector that would state which packages are present in the stack. That could reveal well performing package combinations.

> 
> we can notice that numpy-1.19.4-pypi-org-simple is not the latest version of numpy actually.
> 
> So I wanted to check if we can compare with stack created by pipenv. So I installed `tensorflow==2.4.0` with pipenv and noticed that `numpy==1.19.5` as we can see from the stack below:
> 
> ```
> ...
> ```
> 
> Unfortunately, the inspections runs stacks in this dataset do not have any c used with tensorflow 2.4.0, is that normal @fridex ?
> 

It was eigher not yet analysed, or random software stack sampling did not hit that specific numpy release. We can definitelly trigger another inspection, specifically with `numpy==1.19.5` to see results.

This is very nice :+1:

**Comment by fridex** [comment]
> To my understanding of the plot, we would like to know why software stacks encoded with yellow dots are performing better than the rest.

Or purple dots comparing to the rest assuming lower elapsed time is better (?).

**Comment by pacospace** [comment]
> > > Thanks!
> > 
> > 
> > Another interesting thing about performance identified from this dataset:
> > ![TF==2 4 0 performance (2D plot)](https://user-images.githubusercontent.com/27498679/111445916-27adf000-870c-11eb-84ce-90160df47297.png)
> > It apperas there is one stack which is way more performant than others, identified by ID: 558, which corresponds to software stack:
> > ```
> > ...
> > ```
> 
> Not sure if I follow this - the plot shows 3 potentially separable performance lines. If I read the the plot correctly, there could be package combinations that create this separation (if we are not hitting different hardware nodes in the cluster that have different performance) - yellow, purple and orange lines. To my understanding of the plot, we would like to know why software stacks encoded with yellow dots are performing better than the rest. If there are no hardware configuration differences, we could try to cluster software stacks based on vector that would state which packages are present in the stack. That could reveal well performing package combinations.

I like this idea!! We can basically identify what packages in the stack actually influence the performances (explainability)

need to check but might be the three numpy versions considered and described above could be associated with those three performance clustered lines.

```
$ final_dataframe['numpy'].unique()

array(['numpy-1.19.4-pypi-org-simple', 'numpy-1.19.0-pypi-org-simple',
       'numpy-1.18.5-pypi-org-simple'], dtype=object)
```
> 
> > we can notice that numpy-1.19.4-pypi-org-simple is not the latest version of numpy actually.
> > So I wanted to check if we can compare with stack created by pipenv. So I installed `tensorflow==2.4.0` with pipenv and noticed that `numpy==1.19.5` as we can see from the stack below:
> > ```
> > ...
> > ```
> > 
> > 
> > Unfortunately, the inspections runs stacks in this dataset do not have any c used with tensorflow 2.4.0, is that normal @fridex ?
> 
> It was eigher ~not yet analysed~ not known to Thoth, or random software stack sampling did not hit that specific numpy release. We can definitelly trigger another inspection, specifically with `numpy==1.19.5` to see results.
> 
> This is very nice
