### ISSUE TITLE
Provide database dump to the community

### ISSUE THREAD

**Issue by fridex** [thoth-station/datasets#32]
**Is your feature request related to a problem? Please describe.**

As an external Thoth contributor, I would like to setup my environment so that I can develop components of Thoth.

**Describe the solution you'd like**

Provide a minimal database dump that can be used to test changes in components.

- [ ] make sure the dump does not hold any sensitive information (e.g. GitHub repos we maintain)
- [ ] remove all solver results, except for rhel:8+py38

**Acceptance Criteria**

- [ ] database dump is provided in a public bucket, so that it can be accessed by anyone
- [ ] instructions how to access the public bucket are present in the thoth-station/storages and thoth-station/datasets REAMDE files

**Comment by pacospace** [comment]
cc @xquery

**Comment by codificat** [comment]
/remove-lifecycle rotten
(that label was added by a buggy version of the bot)
