### ISSUE TITLE
Provide new solver dataset based on new solver documents gathered.

### ISSUE THREAD

**Issue by pacospace** [thoth-station/datasets#34]
**Is your feature request related to a problem? Please describe.**
Solver introduced new features and store new knowledge that can be interesting for some projects relying on this data.

**Describe the solution you'd like**
Provide new solver dataset based on new solver documents gathered.

**Describe alternatives you've considered**

**Additional context**
as @fridex pointed out, we miss content in solver documents that can be used for current intern projects.

**Comment by pacospace** [comment]
@fridex about 10000 solver documents from backup-stage that have solver version `v0.10.1` sounds good?

**Comment by fridex** [comment]
> @fridex about 10000 solver documents from backup-stage that have solver version `v0.10.1` sounds good?

A minimal version of thoth-solver that supports packages detection is 1.9.0. It might be better to create the dataset from the newly created batch in the stage environment (not the backup).

**Comment by pacospace** [comment]
> > @fridex about 10000 solver documents from backup-stage that have solver version `v0.10.1` sounds good?
> 
> A minimal version of thoth-solver that supports packages detection is 1.9.0. It might be better to create the dataset from the newly created batch in the stage environment (not the backup).

New version of the dataset is available on kaggle: https://www.kaggle.com/thothstation/thoth-solver-dataset-v10

**Comment by pacospace** [comment]
> > > @fridex about 10000 solver documents from backup-stage that have solver version `v0.10.1` sounds good?
> > 
> > 
> > A minimal version of thoth-solver that supports packages detection is 1.9.0. It might be better to create the dataset from the newly created batch in the stage environment (not the backup).
> 
> New version of the dataset is available on kaggle: https://www.kaggle.com/thothstation/thoth-solver-dataset-v10

@tlegen-k feel free to ask here for specific packages you want in solver reports, we can provide those to you :)

**Comment by pacospace** [comment]
This was solved by @tlegen-k !
