### ISSUE TITLE
Notebook content does not match the datasets structure

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/datasets#53]
**Describe the bug**
The content of the notebook cells do not match the structure of the datasets, generating `KeyError`s for most of them and stopping the retrieval of documents for some.

**To Reproduce**
Run cells of the notebooks.

**Expected behavior**
All documents are retrieved and the sub-documents to analyze can be extracted by calling the right values on the aggregated results from Ceph with `aggregate_thoth_..._results` methods.

**Comment by goern** [comment]
any updates on this? do we consider it done?

**Comment by mayaCostantini** [comment]
It is still in progress, I will resume working on it soon 👍🏻
